#!/usr/bin/env python3
"""Assemble the models the published demo serves, plus an index for its picker.

Every language tag resolves to a (recospec, net) pair, and those pairs overlap
heavily: one Latin net serves 269 tags, one Devanagari net serves 50. So the
assets are deduplicated by pack name and the index maps tags onto them, which is
why offering all 725 tags costs about the same as offering 27.

Gesture, emoji, autodraw and shapes packs are skipped: they are classifiers, not
CTC recognizers, and the demo would only be able to fail on them.

    .venv/bin/python tools/build_demo_assets.py
"""
from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src import packs, recospec  # noqa: E402

OUT = ROOT / "web" / "models"
# Not CTC recognizers; Recognizer::load rejects them by design.
SKIP = ("emoji", "autodraw", "shapes", "gesture")


def main() -> None:
    resolver = packs.PackResolver()
    OUT.mkdir(parents=True, exist_ok=True)

    entries: dict[str, dict] = {}
    copied: dict[str, str] = {}
    skipped: list[str] = []

    for tag in resolver.languages:
        if any(marker in tag for marker in SKIP):
            continue
        names = resolver.resolve(tag)
        if any(marker in names["tflite"] for marker in SKIP):
            continue
        try:
            paths = resolver.ensure(tag)
        except Exception as error:                      # a pack we cannot fetch
            skipped.append(f"{tag}: {type(error).__name__}")
            continue

        files = {}
        for kind in ("recospec", "tflite"):
            source = paths[kind]
            name = f"{names[kind]}{source.suffix}"
            if name not in copied:
                shutil.copy2(source, OUT / name)
                copied[name] = kind
            files[kind] = name

        # The charset size is the honest label for what a script can write, and
        # it is already parsed here, so the picker does not have to guess.
        try:
            spec = recospec.load(paths["recospec"])
            characters = len(spec.charset)
        except Exception:
            characters = 0
        entries[tag] = {**files, "characters": characters}

    index = {
        "note": "Generated by tools/build_demo_assets.py. Tags share packs; see the file names.",
        "languages": entries,
    }
    (OUT / "index.json").write_text(json.dumps(index, separators=(",", ":"), sort_keys=True) + "\n")

    total = sum((OUT / name).stat().st_size for name in copied)
    nets = sum(1 for kind in copied.values() if kind == "tflite")
    print(f"{len(entries)} language tags -> {len(copied)} files ({nets} nets), {total/1e6:.1f} MB")
    if skipped:
        print(f"skipped {len(skipped)}: {', '.join(skipped[:5])}")


if __name__ == "__main__":
    main()
